spring:
    datasource:
       url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
       username: root
       password: root
       driver-class-name: com.mysql.jdbc.Driver

    redis:
      cluster:
        nodes:
        max-redirects: 3

server:
  port: 9000
