server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 5s
    lettuce:
      pool:
        min-idle: 0
        max-active: 20
        max-idle: 8
        max-wait: -1ms
    sentinel:
      master: mymaster
      nodes: 192.168.32.22:6395,192.168.32.23:6394,192.168.32.14:6392
