mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.mindflow.springboot.mybatis.model
    type-handlers-package: com.mindflow.springboot.mybatis.typehandler
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100

spring:
    datasource:
       url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
       username: root
       password: root
       driver-class-name: com.mysql.jdbc.Driver