server:
  port: 8080

spring:
    datasource:
       url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
       username: root
       password: root
       driver-class-name: com.mysql.jdbc.Driver
       initialSize: 20
       minIdle: 1
       maxActive: 100
       maxWait: 5000